# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rfgraph}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Luke van der Hoeven"]
  s.date = %q{2010-04-25}
  s.description = %q{A simple Ruby wrapper to help use the Facebook Graph API.}
  s.email = %q{hungerandthirst@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "VERSION",
     "init.rb",
     "lib/rfgraph.rb",
     "lib/rfgraph/auth.rb",
     "lib/rfgraph/request.rb",
     "rfgraph.gemspec",
     "test/rfgraph_test.rb"
  ]
  s.homepage = %q{http://github.com/plukevdh/rfgraph}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A simple Ruby wrapper to help use the Facebook Graph API.}
  s.test_files = [
    "test/rfgraph_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

